name: Generate new patches
on:
  workflow_dispatch:
    inputs:
      pr:
        description: 'Create PR'
        required: true
        default: true

jobs:
  generate:
    runs-on: macOS-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Divvun CI
      uses: divvun/actions/setup@master
      with:
        key: ${{ secrets.DIVVUN_KEY }}

    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        profile: minimal
        override: true
    
    - name: Build patch detector
      run: npm run build
      working-directory: mso-patcher
    
    - run: |
        for MSO_URL in $(node ./mso-patcher/dist/unpatched.js);
        do
          export MSO_VER=$(echo $MSO_URL | sed -e 's/https:\/\/officecdn-microsoft-com.akamaized.net\/pr\/C1297A47-86C4-4C1F-97FA-950631F94777\/MacAutoupdate\/Microsoft_Word_\(.*\)_Installer\.pkg/\1/')
          wget -o mso.pkg "$MSO_URL"
          sudo installer -verbose -pkg mso.pkg -target /
          rm mso.pkg
          sudo mv "/Applications/Microsoft Word.app" $MSO_VER
          echo "##vso[task.setvariable variable=mso]$MSO --mso \"$PWD/$MSO_VER\""
        done
      name: Download MS Office versions

    - name: Build rust tools
      uses: actions-rs/cargo@v1
      with:
        command: build
      
